services:
  krapfen-app:
    build: .
    ports:
      - "8024:3838"
    volumes:
      - krapfen-data:/srv/shiny-server/krapfen/data
    environment:
      - R_PROFILE=/srv/shiny-server/krapfen/.Rprofile
    image: ghcr.io/judithbernett/krapfenrating:docker-build

volumes:
  krapfen-data:
    driver: local
