version: '3.8'

services:
  krapfen-app:
    build: .
    ports:
      - "8024:3838"
    volumes:
      - krapfen-data:/srv/shiny-server/krapfen/data
    image: ghcr.io/judithbernett/krapfenrating:docker-build

volumes:
  krapfen-data:
    driver: local
